name = "Steampunk Magic 2"
author = "IndigoLily"
version = "0.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c01c3c75902dcfd1e77657401f23aef17b16bffbc0ebe86fd648c589a0c648c9"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
