name = "Steampunk Magic 2"
author = "IndigoLily"
version = "0.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9cee21cc0f35d32259dbfd2b514e273042542a68548e614b157daf111c78399"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
