name = "Steampunk Magic 2"
author = "IndigoLily"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca71f0e832105c6f2cbfaa0fc3630e35b6605ef2ce38e107ac1f4cf54f34eda1"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
