name = "Steampunk Magic 2"
author = "IndigoLily"
version = "0.6.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7338dd959e5227db76f4bca9a5a1f9bb1ecd6549f445bbd5903dc7052c606fa"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
