name = "Steampunk Magic 2"
author = "IndigoLily"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ab4056449677539f29943b8b49a01422136de0f64e4f4523c12d576ea4b0d0d"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
