name = "Steampunk Magic 2"
author = "IndigoLily"
version = "0.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0761c8a48b8b47b9b43f1708b9384376bc50fcf0df400b57ac528d6de9cbc7cb"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
