name = "Steampunk Magic 2"
author = "IndigoLily"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dd39ddac8e372393a618be74f4c9a9c00f0145aa9b5140bcb4fdc2af157ab02"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
