name = "Steampunk Magic 2"
author = "IndigoLily"
version = "0.12.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91e8fb0342df83f00388444d0b9cc810ac8169434ee986563f4152aacadfb964"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
