name = "Steampunk Magic 2"
author = "IndigoLily"
version = "0.6.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "467bae49a2d1ecd09788ae4e7fce72ab4103b7fca3fd0b82a4462bc991ec764e"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
