name = "Steampunk Magic 2"
author = "IndigoLily"
version = "0.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27f4de40da0d02087dea684cd671b6a7519d6e35c77296a659bdba10d930c32e"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
